---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart github-runner
  ansible.builtin.systemd:
    name: github-runner
    state: restarted
  become: true
