---
mutt_setup_google_oauth2_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36613866336335343134376135313733396561666339613166623438323831336663346237326566
  3130323465666239623930373133633939393734623334640a663336383233363631343737376334
  37323336346237663966663037346332346535393331386338623538356432373935393366363963
  3266633830303834630a386363376161343239666264343337616332646462303462363731623736
  33666136363035636161383133313363383762393138323133333065316437653330613965396263
  6464313833383838333434393633616438313635616461343963
