---
# meta file for grafana_setup

galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: grafana_setup
  namespace: sbates130272
  description: >-
    A role to install and configure Grafana, Prometheus,
    and Node Exporter
  license: BSD-3-Clause
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - monitoring
    - grafana
    - prometheus
    - metrics

dependencies: []
