---
# meta file for nvmeof_setup

galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: nvmeof_setup
  namespace: sbates130272
  description: A role to setup NVMe-oF targets and hosts
  license: BSD-3-Clause
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - nvme
    - storage
    - rdma
