galaxy_info:
  author: Stephen Bates
  description: Stephen Bates
  company: Raithlin Semiconductors
  license: BSD-3-Clause
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
