---
# defaults file for consul_setup
consul_setup_server: false
consul_setup_server_node: derry
# Set to false in CI or when you only want install/config without starting
consul_setup_start_service: true
consul_setup_encrypt: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65326136303361323063303935316464616634303662623265383739666365643439363438376265
          3963326463313261306337336166373563393934356230340a386237663234303132646239326533
          66623962636132353465313964383264363163333036363465326130326664353338623635616131
          6135396366393763610a613732396538383366393166653366333166306538663837386438383065
          37313437623636363662636361663531636636643866393837303234356261633164633433623032
          3665636164313030646231386638313664303664376437306562
